Document: arbiter2
Title: Debian arbiter2 Manual
Author: <insert document author here>
Abstract: This manual describes what arbiter2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/arbiter2/arbiter2.sgml.gz

Format: postscript
Files: /usr/share/doc/arbiter2/arbiter2.ps.gz

Format: text
Files: /usr/share/doc/arbiter2/arbiter2.text.gz

Format: HTML
Index: /usr/share/doc/arbiter2/html/index.html
Files: /usr/share/doc/arbiter2/html/*.html
